apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
        - name: health-care-container
          image: suryateja1558/health-care:1.0
          ports:
            - containerPort: 8082

-----

apiVersion: v1
kind: Service
metadata:
  name: health-care-service
spec:
  selector:
    app: health-care
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
  type: NodePort

